 csvserver:
   image: "fosfordevops/csvgenerator:latest"
   container_name: "test"
   ports:
    - 9393:9300
   volumes:
    - ./inputFile:/csvserver/inputdata
   environment: 
    - CSVSERVER_BORDER=Orange

 prometheus:
   image: prom/prometheus:v2.22.0
   ports:
     - 9090:9090
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
